# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  
  #Balanceador de carga
  config.vm.define :load_balancer do |load_balancer|
    load_balancer.vm.box = "centos1706v3"
    load_balancer.vm.network :private_network, ip: "192.168.34.11"
    load_balancer.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "4", "--name", "load_balancer" ]
    end
   config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "haproxy"
      chef.json = {
	"web_servers" => [
	  {"ip":"192.168.34.12"},
	  {"ip":"192.168.34.13"}
	]
      }
   end 
  end

  #Servidor web 1
  config.vm.define :web_server1 do |web_server1|
    web_server1.vm.box = "centos1706v3"
    web_server1.vm.network :private_network, ip: "192.168.34.12"
    web_server1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "4", "--name", "web_server_a" ]
    end
   config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "httpd"
      chef.json = {
	"service_name" => "webserver1",
	"ip" => "192.168.34.12"
	}
   end
  end

  #Servidor web 2
  config.vm.define :web_server2 do |web_server2|
    web_server2.vm.box = "centos1706v3"
    web_server2.vm.network :private_network, ip: "192.168.34.13"
    web_server2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "4", "--name", "web_server_b" ] 
    end
   config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "httpd"
      chef.json = {
	"service_name" => "webserver2",
	"ip" => "192.168.34.13"
	}
   end
  end
end

